# Generated by Django 4.1 on 2022-09-17 12:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="House",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city", models.CharField(blank=True, max_length=100, null=True)),
                ("street", models.CharField(blank=True, max_length=100, null=True)),
                ("zip", models.IntegerField()),
                (
                    "picture_front_of_house",
                    models.ImageField(
                        blank=True,
                        help_text="picture of the front of the house",
                        null=True,
                        upload_to="pictures_front_of_house/",
                    ),
                ),
                (
                    "picture_of_bedroom",
                    models.ImageField(
                        blank=True,
                        help_text="picture of the bedroom",
                        null=True,
                        upload_to="pictures_of_bedroom/",
                    ),
                ),
                (
                    "other_picture",
                    models.ImageField(
                        blank=True,
                        help_text="other picture of the house",
                        null=True,
                        upload_to="other_pictures/",
                    ),
                ),
                (
                    "message_of_presentation_of_house",
                    models.TextField(blank=True, null=True),
                ),
                ("is_available", models.BooleanField(default=True)),
                ("is_removed", models.BooleanField(default=False)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="list_of_houses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "<< A house >>",
                "verbose_name_plural": "list of houses",
            },
        ),
    ]
