# Generated by Django 4.1 on 2022-09-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_housing", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="house",
            name="capacity",
            field=models.IntegerField(default=1),
        ),
    ]
