# Generated by Django 4.1 on 2022-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_housing", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ReceivedMessage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("datetime", models.DateTimeField(auto_now_add=True)),
                ("is_already_read", models.BooleanField(default=False)),
                ("firstname", models.CharField(max_length=255)),
                ("lastname", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=255)),
                ("phone_number", models.CharField(max_length=255)),
                ("message", models.TextField()),
            ],
            options={
                "ordering": ["datetime"],
            },
        ),
    ]
