# Generated by Django 4.1 on 2022-09-25 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_housing", "0002_receivedmessage"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="receivedmessage",
            options={"ordering": ("-datetime",)},
        ),
    ]
