# Generated by Django 4.1 on 2022-09-19 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("app_housing", "0002_house_capacity"),
    ]

    operations = [
        migrations.RenameField(
            model_name="house",
            old_name="street",
            new_name="nbr_n_street",
        ),
    ]
