# Generated by Django 4.1 on 2022-09-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_housing", "0003_rename_street_house_nbr_n_street"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="picture_front_of_house",
            field=models.FileField(
                blank=True,
                help_text="picture of the front of the house",
                null=True,
                upload_to="pictures_front_of_house/",
            ),
        ),
    ]
