# Generated by Django 4.1 on 2022-09-20 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_housing", "0004_alter_house_picture_front_of_house"),
    ]

    operations = [
        migrations.AlterField(
            model_name="house",
            name="picture_front_of_house",
            field=models.ImageField(
                blank=True,
                help_text="picture of the front of the house",
                null=True,
                upload_to="pictures_front_of_house/",
            ),
        ),
    ]
