# Generated by Django 4.1 on 2022-09-17 12:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("app_accounts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="member",
            name="hosts",
            field=models.ManyToManyField(
                related_name="contacts", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
